### ISSUE TITLE
문제 관련 질문드립니다.

### ISSUE THREAD

**Issue by Aningaaq** [riiicruitwww/render-passage-Aningaaq#1]
안녕하세요. 

과제를 저번주 금요일에 받았는데 개인 일정을 제대로 조절하지 못해 이제서야 과제를 시작하게 되었습니다.

혹시 1차 PR 제출 기한을 좀 미룰 수 있을까요? 주말까지 최대한 완성해서 제출하도록 하겠습니다.

----------------------------------------

질문:

1. task_container.json 의 데이터 구조에 대한 명세를 받을 수 있을까요? 
2. 구현해야할 프로젝트의 디자인은 산타토익의 part6 문제풀이 UI 를 본따면 되나요?
3. "문제를 풀이 => 채점 => 다음 문제" 이런 방식이 반복되는 기능을 구현하는건가요?

@vchoisk

**Comment by vchoisk** [comment]
안녕하세요 @Aningaaq 님,

제출기한은 다음주 화요일까지 제출이 가능하실까요? 알려주시면 제가 인사팀쪽에 이야기를 하도록 하겠습니다.


1. 데이터 명세의 경우 아래와 같이 간략하게 설명드립니다.
```
/*
  package의 경우, 학습 컨텐츠(하나의 학습단위)의 명칭으로, 토익에서는 "문제풀이"와 "강의보기"의 두가지 컨텐츠가 존재합니다.
  예시로 주어진 package의 경우 "문제풀이"이며, 문제에 해당되는 지문(passage)과 문제(question)로 이루어져 있습니다.  
*/
package: {
  name: String, // 문제? 강의?
  type: String, // 토익 파트
  human_id: String, // 고유값
  preview: String, // Package의 간소화된 형태의 string
  questions: Array.of(Question), // "문제풀이" 중 문제
  chunk_map: Object, // Package를 그리는데 사용하는 단위 "Chunk"가 모두 id로 맵핑된 Map
  passag_box: Object // "문제풀이" 중 지문
}

/*
  question, passage, passage_translation의 경우, 각자 필요한 고유값을 가지고 있으며 기본적으로 chunk의 구성으로 그려지며, chunk의 구성의 경우 view_tree로 이루어져 있습니다. (고로 세가지 데이터중, question의 대한 명세만 우선적으로 공유 드립니다.)
*/
question: {
  id: Number, // 고유값
  pack_type: String, // 토익 파트
  passage_box_id: Number, // 해당 문제가 귀속된 pasage_box의 고유값
  raw_fbid: String, // 고유값
  correct_answer: String,  // 정답
  order: Number, // 문제의 순서(문제가 속한 pasasge_box기준)
  pack_id: Number, // 해당 문제가 귀속된 pack의 고유값
  view_tree: Object, // 문제를 구성하는 chunk의 구조(트리 형태)
  labels: Array.of(label_ids: Number) // 문제가 포함하는 토익에서의 분류 label의 교유값
}
```

2. UI의 경우 온전히 선택적이며, raw한 형태로 제출 하시더라도, 부정적인 요인이 되지 않습니다.

3. 기능의 경우 `채점`을 할수있다는 것만 필수적이라고 생각하시면 될것같습니다. 문제를 한번에 다 풀고 체점을 하거나, 한 문제씩 풀게하는등은 자유롭게 구현해주시면 됩니다.

**Comment by Aningaaq** [comment]
답변 감사드립니다.

제출 기한에 관해서는 인사팀께 어제 메일 드렸고, 월요일까지 제출로 조정하였습니다.

데이터 명세에 대한 답변을 참고하여 task_container.json 을 살펴 보았고 추가 질문이 있습니다.

1. `chunk_map`을 쭉 훑어보니 이렇게 정리되는것 같습니다.

- 영어 지문 + 한국어 번역 
- 객관식 답안
- 답안별 문제 해설 
이 중 지문과 한국어 번역, 그리고 객관식 답안 chunk 는 question의 view_tree 를 통해 chunk_id 가 연결이 되어 있는데 
답안별 문제 해설 chunk 들의 경우엔 question과 연결이 되어 있지 않은것 같습니다.
답안별 문제 해설 chunk 들은 채점이후에 표시되지 않아도 되는건가요? 

2. passage 와 passage_translation의 경우에는 명세를 공유해주지 않으셨는데 이부분은 기능 구현에 필요 없다고 판단하신건가요? 
3. passage_translation 안에 style 정보가 굉장히 많이 들어있는데 이건 굳이 따라야하는 스타일은 아닌건가요? 

4. 문제를 푸는데 제시되는 지문은 preview의 지문인것 같습니다. chunk 에 들어있는 문제 지문은 4개의 단락으로 구분이 되어 있는데 이렇게 나뉘어 있는 이유는 무엇인가요? 

@vchoisk

**Comment by Aningaaq** [comment]
그리고 뤼이드의 PR 작업 방식 예시라 올려주신 링크가 죽어있습니다.
혹시 작업 방식 예시를 볼 수 있을까요? 
https://apply.riiid.app/677  <- 이 링크가 404 Not Found 에러가 돌아옵니다. 
@vchoisk
